### ISSUE TITLE
Невозможно отправить звук в tts

### ISSUE THREAD

**Issue by iliailia1212** [thesoultaker48/yandex-dialogs-php#1]
При добавлении tts:
`$alice->add_message('tes', '<speaker audio="dialogs-upload/*id*.opus">');`
Функция `strip_tags` для `['response']['tts']` удаляет этот тег и остаётся пустая строка.
`YandexDialog.php:441`

**Comment by kasitoru** [comment]
Попробуйте заменить строку `YandexDialog.php:439` на следующую:
`$this->response['response']['tts'] = strip_tags($this->response['response']['tts'], '<speaker>');`
У меня сейчас, к сожалению, нет возможности проверить. Отпишитесь по результату.

**Comment by iliailia1212** [comment]
Да, спасибо, так работает
