### ISSUE TITLE
Возврат к началу чата.

### ISSUE THREAD

**Issue by solaryssky** [thesoultaker48/yandex-dialogs-php#2]
Подскажите пожалуйста как можно через данную библиотеку реализовать возврат к началу чата если условие не выполнено? Т.е пользователю задается вопрос, если ответ не верный или получены не полные данные, то вернуть его к первому шагу чата.

**Comment by kasitoru** [comment]
На текущий момент механизм нелинейных сценариев встроенными средствами библиотеки не реализован, но вы можете использовать собственные алгоритмы для навигации по дереву условий.

**Comment by solaryssky** [comment]
Понял. А как можно это реализовать через дерево условий? Как построить условие я понимаю, мне не понятно как вернуться в начало. Это получается завершение сессии и выход по идее ? Или что-то другое есть чтобы не производить выход? Или чисто на своей логике скриптв делать возврат через условия?

**Comment by kasitoru** [comment]
Как вариант - хранить в сессии некоторую переменную, содержащую указатель местоположения в диалоге. И в зависимости от этого значения, отдавать пользователю нужную часть диалога. Соответственно, сменив это значение на нужное нам, можно будет переместиться в любое место диалога. Это первое, что пришло в голову.

**Comment by solaryssky** [comment]
Спасибо
